
project_id = "otqooqeosxkgftrpctso"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.queue-operations]
verify_jwt = false

