// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otqooqeosxkgftrpctso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cW9vcWVvc3hrZ2Z0cnBjdHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzcyNjcsImV4cCI6MjA1OTM1MzI2N30.-rqG4v3egqrcpLc1D6k73pwpnW3V4pNYtwViYXDiJ6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);